import type { Metadata } from "next";
import "./globals.css";
import { Web3Provider } from "@/contexts/web3-context"
import { ToastProvider, ToastViewport } from "@/components/ui/toast"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Web3Provider>
          <ToastProvider>
            {children}
            <ToastViewport />
          </ToastProvider>
        </Web3Provider>
      </body>
    </html>
  )
}


